name: Streamlit Keep Alive

on:
  schedule:
    - cron: '0 0 * * *' # Changed to run every 24 hours for better reliability
  workflow_dispatch:      # Allows you to test it manually

jobs:
  ping_app:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: curl -I https://abei-sentimentanalysis.streamlit.app/
